CREATE PROCEDURE [dbo].[RealizarRestore] 
@PATH1 nchar(300),
@PATH2 nchar(300),
@PATH3 nchar(300)
AS
BEGIN
    SET NOCOUNT ON;
    
    ALTER DATABASE ELARA
    SET RESTRICTED_USER
    WITH ROLLBACK IMMEDIATE;

    RESTORE DATABASE ELARA FROM
	
	DISK = @PATH1,
	DISK = @PATH2,
	DISK = @PATH3
	
	WITH RECOVERY, NOUNLOAD, REPLACE, STATS = 10;
	
    ALTER DATABASE ELARA
    SET MULTI_USER;

END