//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PD.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Espanol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Espanol() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PD.Idioma.Espanol", typeof(Espanol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Clientes.
        /// </summary>
        internal static string abmclientes {
            get {
                return ResourceManager.GetString("abmclientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Familias.
        /// </summary>
        internal static string abmfamilias {
            get {
                return ResourceManager.GetString("abmfamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Medios.
        /// </summary>
        internal static string abmmedios {
            get {
                return ResourceManager.GetString("abmmedios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Ubicaciones.
        /// </summary>
        internal static string abmubicaciones {
            get {
                return ResourceManager.GetString("abmubicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM Usuarios.
        /// </summary>
        internal static string abmusuario {
            get {
                return ResourceManager.GetString("abmusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación de Patentes.
        /// </summary>
        internal static string Asignacion_de_Patentes {
            get {
                return ResourceManager.GetString("Asignacion_de_Patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloquear Desbloquear Operaciones.
        /// </summary>
        internal static string BloquearDesbloquearOperacionesaUsuario {
            get {
                return ResourceManager.GetString("BloquearDesbloquearOperacionesaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al sistema.
        /// </summary>
        internal static string btn_cancelar {
            get {
                return ResourceManager.GetString("btn_cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btn_salir {
            get {
                return ResourceManager.GetString("btn_salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnConfirmar {
            get {
                return ResourceManager.GetString("btnConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string btnIngresar {
            get {
                return ResourceManager.GetString("btnIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calcular Dígitos Verificadores.
        /// </summary>
        internal static string calculardigitosverificadores {
            get {
                return ResourceManager.GetString("calculardigitosverificadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Clave.
        /// </summary>
        internal static string CheckCambiarClave {
            get {
                return ResourceManager.GetString("CheckCambiarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar Idioma.
        /// </summary>
        internal static string configuraridioma {
            get {
                return ResourceManager.GetString("configuraridioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Bitácora.
        /// </summary>
        internal static string consultarbitacora {
            get {
                return ResourceManager.GetString("consultarbitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Negocio.
        /// </summary>
        internal static string crearnegocio {
            get {
                return ResourceManager.GetString("crearnegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear Operaciones .
        /// </summary>
        internal static string DesbloquearOperacionAUsuariocs {
            get {
                return ResourceManager.GetString("DesbloquearOperacionAUsuariocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer BackUp.
        /// </summary>
        internal static string hacerbackup {
            get {
                return ResourceManager.GetString("hacerbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer Restore.
        /// </summary>
        internal static string hacerrestore {
            get {
                return ResourceManager.GetString("hacerrestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string LblClave {
            get {
                return ResourceManager.GetString("LblClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Anterior.
        /// </summary>
        internal static string LblClaveAnterior {
            get {
                return ResourceManager.GetString("LblClaveAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Nueva.
        /// </summary>
        internal static string LblClaveNueva {
            get {
                return ResourceManager.GetString("LblClaveNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea salir ?.
        /// </summary>
        internal static string lblConfirm {
            get {
                return ResourceManager.GetString("lblConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string LblUsuario {
            get {
                return ResourceManager.GetString("LblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Usuarios.
        /// </summary>
        internal static string menuusuarios {
            get {
                return ResourceManager.GetString("menuusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Perfil Usuario.
        /// </summary>
        internal static string modificarperfilusuario {
            get {
                return ResourceManager.GetString("modificarperfilusuario", resourceCulture);
            }
        }
    }
}
